# Generated by Django 5.0.6 on 2024-06-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='fitnessprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.userprofile', verbose_name='User'),
        ),
    ]
