# Generated by Django 5.0.6 on 2024-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_user_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='fitnessprogram',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='fitnessprogram',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='fitnessprogram',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='fitnessprogram',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Record Type'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Record Type'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_en',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_ru',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='medication',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ru',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
    ]
